### ISSUE TITLE
NUMBER type as int64

### ISSUE THREAD

**Issue by maliutin** [rana/ora#57] opened 2016-02-04 14:42 UTC
Hi

When i used version 3.0 I received value with NUMBER type. And it was possible to convert to int64 GO type.

For example:
```
CREATE TABLE BRANCH.ACTIVITY (
  ACTIVITY_ID NUMBER NOT NULL
)
```
```
id := rset.Row[0].(int64)
```
In 3.0 it is worked. But in 3.1 it throws the error:

> interface conversion: interface is float64, not int64

Is this a bug or planned change?

**Comment by tgulacsi** [comment] 2016-02-04 15:47
Good question.

NUMBER in Oracle can hold 38 decimal digits, so int64 is not enough with its 19 decimal digits.
float64 is a little bit better - not precise enough, but won't overflow.
The best would be something like gopkg.in/inf.v0 , but that may be overkill...

Any suggestions?

**Comment by maliutin** [comment] 2016-02-04 15:54
Are there another changes for other Oracle types?
I need to check the code for other such cases?

**Comment by rana** [comment] 2016-02-04 17:37
It would be good to preserve the original behavior of zero scale number to
default return an integer. Oracle NUMBER without a specified scale defaults
to zero scale. We can infer that the user of the driver is working in
integers. The user can manually change the return type if needed. What do
you think?

**Comment by maliutin** [comment] 2016-02-05 08:19
I suppose that in 3.1 the standard GO logic was implemented (I have not looked at the source):
```
package main

import "fmt"

func main() {
	var b float64 = 1

	var b1 interface{} = b

	var b2 int64 = b1.(int64) // panic: interface conversion: interface is float32, not int32

	fmt.Println("b2: %t", b2)
}
```
It is general behaviors for GO code. But float64 is not original datatype for the value, which we receive from database and we do not have official declaration from Oracle or GO how we have to match data types between Oracle and GO. Thus, only the user can decide about that.
I think that the behavior of 3.0 functionality was correct.

**Comment by maliutin** [comment] 2016-02-05 12:17
Additional argument.

We have a procedure with an out parameter:
```
PROCEDURE create_activity(p_activity_id   OUT NUMBER)
```
And we can receive value as int64 in the output parameter.
```
var outActivityId int64
_, err = stmt.Exe(&outActivityId)
```
Why in this case we can receive NUMBER value as int64?

**Comment by tgulacsi** [comment] 2016-02-08 14:27
Sorry to be late, I'm absolutely not against going back to int64, and absolutely accept that's my fault, but right now I'm knee deep in making ora run with Go 1.6 (the stricter cgo rules and runtime check makes this non trivial), so if someone can help by pointing me the right code, that'd be a great help!

Either find the logic that needs tweaking by debugging/fmt.Printfing, or by searching through git diff 3..3.1 would work.

**Comment by rana** [comment] 2016-02-09 05:47
You are brave for taking on the 1.6 cgo changes. I don't think I have the
courage, or time for that at the moment and am relieved to hear you've got
it covered. I've been pulled in other directions and can't contribute at
the moment... Excited to see your latest masterpiece. Cheers

**Comment by tgulacsi** [comment] 2016-02-16 14:44
According to Tom Kyte (https://asktom.oracle.com/pls/apex/f?p=100:11:0::::P11_QUESTION_ID:1619552483055), a NUMBER column is a NUMBER(*) column, which is an unconstrained, maximum 38 digits numeric column.
So I think the closest match is a float64.

The logic has been factored out to the end of rsetCfg.go, so you can experiment with it as you wish.

Also, the tests (z_numeric_session_test.go) all define the GoColumnType for the resultset, so the numericColumnType function is not called - it is called only when no go column type is specified.

For database/sql usage, the number conversions are done automatically, so the only remaining use case is stmt.Exe, stmt.Qry - but for this, there is a solution already: specify the GoColumnType for that column!


For the procedure call case: that is not a define, but a bind, and there the receiving (bound) parameter's type rules!

**Comment by kokteyldev** [comment] 2016-02-17 21:41
Even when using database/sql there are ways to force mapping a number column to an int using sqlx, scanning manually. I am currently getting the following error using [sqlx ](https://github.com/jmoiron/sqlx)(Very simple mapping layer):

`Scan error on column index 0: converting string "8.881347e+06" to a int: strconv.ParseInt: parsing "8.881347e+06": invalid syntax
`

Which is infact the number **8881351**. I had no issues when using goracle, I just started using rana for 1.6 compatibility. This issue is present in tags v3, v3.1 and branch go1.6. 

I am playing around with rsetCfg.go right now to see if I can control it based on the destination field somehow.

**Comment by omerkirk** [comment] 2016-02-17 21:42
Even when using database/sql there are ways to force mapping a number column to an int using sqlx, scanning manually. I am currently getting the following error using [sqlx ](https://github.com/jmoiron/sqlx)(Very simple mapping layer):

`Scan error on column index 0: converting string "8.881347e+06" to a int: strconv.ParseInt: parsing "8.881347e+06": invalid syntax
`

Which is infact the number **8881351**. I had no issues when using goracle, I just started using rana for 1.6 compatibility. This issue is present in tags v3, v3.1 and branch go1.6. 

I am playing around with rsetCfg.go right now to see if I can control it based on the destination field somehow.

**Comment by omerkirk** [comment] 2016-02-18 00:18
I created a test case and found that my issue is not the same yet it is still an issue related to scanning float64 to int64.

DB:
`
CREATE TABLE PUSH_NOTIFICATION.TBL_NUMBER_TEST
(
  NUMBER_SIMPLE  NUMBER,
  NUMBER_SCALE0  NUMBER(*,0)
);

INSERT INTO TBL_NUMBER_TEST (NUMBER_SIMPLE, NUMBER_SCALE0)
VALUES (1, 2);
INSERT INTO TBL_NUMBER_TEST (NUMBER_SIMPLE, NUMBER_SCALE0)
VALUES (10, 20);
INSERT INTO TBL_NUMBER_TEST (NUMBER_SIMPLE, NUMBER_SCALE0)
VALUES (100, 200);
INSERT INTO TBL_NUMBER_TEST (NUMBER_SIMPLE, NUMBER_SCALE0)
VALUES (1000, 2000);
INSERT INTO TBL_NUMBER_TEST (NUMBER_SIMPLE, NUMBER_SCALE0)
VALUES (10000, 20000);
INSERT INTO TBL_NUMBER_TEST (NUMBER_SIMPLE, NUMBER_SCALE0)
VALUES (100000, 200000);
INSERT INTO TBL_NUMBER_TEST (NUMBER_SIMPLE, NUMBER_SCALE0)
VALUES (1000000, 2000000);
INSERT INTO TBL_NUMBER_TEST (NUMBER_SIMPLE, NUMBER_SCALE0)
VALUES (1.5, 2.5);
`

Go:
`
rows, err := db.Query(sqlNumberTest)
if err != nil {
	fmt.Println(err)
}
defer rows.Close()
for rows.Next() {
    var numberSimple, numberScale0 int
    err := rows.Scan(&numberSimple, &numberScale0)
    if err != nil {
        fmt.Println(err)
    }
    fmt.Println(numberSimple, numberScale0)
}
err = rows.Err()
if err != nil {
	fmt.Println(err)
}
`

This outputs:
`
1 2
10 20
100 200
1000 2000
10000 20000
100000 200000
sql: Scan error on column index 0: converting string "1e+06" to a int: strconv.ParseInt: parsing "1e+06": invalid syntax
0 0
sql: Scan error on column index 0: converting string "1.5" to a int: strconv.ParseInt: parsing "1.5": invalid syntax
0 0

`
The last case is expected but the previous one seems to me like database/sql bug. The thing I don't understand is why would it work in goracle.

**Comment by tgulacsi** [comment] 2016-02-18 06:49
goracle produces stringified numbers (OCINumberToText), so immune to long numbers.

ora produces int64/float64, and somewhere it is converted with the default number formatting of go (that produces "1e+06", but at the moment I cannot find where.

**Comment by omerkirk** [comment] 2016-02-18 07:36
I tracked it down. It is on line 302 in https://golang.org/src/database/sql/convert.go.

So it seems the only way to scan a float larger than 999999 is to get it as int from the db.

Can the logic in goracle be ported here or is it too big a rewrite.

**Comment by tgulacsi** [comment] 2016-02-18 11:48
We could return numbers as strings if has more than 6 digits, but I've asked it beforehand at golang-nuts:
https://groups.google.com/forum/#!topic/golang-nuts/rkAAG4vL4Ig

**Comment by omerkirk** [comment] 2016-02-18 12:04
If the code in convert.go had been:
`return strconv.FormatFloat(rv.Float(), 'f', -1, 64)`
instead of 
`return strconv.FormatFloat(rv.Float(), 'g', -1, 64)`

everything should work fine. The latter has no advantage whatsoever on the conversion maybe the produced string takes up less space but I don't think that is the reason it is implemented this way. 

There are 2 ways to solve this. 

1- Since scaning integer values to float fields is no problem. Ora can favor integers over floats based on the value along with column type. To be able to implement this first ora should be able to make type decisions based on value. And it needs to be able to understand if a value has no decimal places.

2- An issue regarding the code in convert.go can be created in golang. Although this will fix the issue I think it is a coincidental fix. 

I prefer the first one, but I am not experienced about db drivers enough to foresee possible side effects. I will try to find the conversion part in ora and play with it.

**Comment by omerkirk** [comment] 2016-02-18 13:06
@tgulacsi I've made some changes in defloat64.go file which seems to fix the issue. What do you think about the following change :

```
func (def *defFloat64) value() (value interface{}, err error) {
	if def.isNullable {
		oraFloat64Value := Float64{IsNull: def.null < C.sb2(0)}
		if !oraFloat64Value.IsNull {
			var float64Value float64
			r := C.OCINumberToReal(
				def.rset.stmt.ses.srv.env.ocierr,       //OCIError              *err,
				&def.ociNumber,                         //const OCINumber     *number,
				C.uword(8),                             //uword               rsl_length,
				unsafe.Pointer(&oraFloat64Value.Value)) //void                *rsl );
			if r == C.OCI_ERROR {
				err = def.rset.stmt.ses.srv.env.ociError()
			}
			value = float64Value
		}
		value = oraFloat64Value
	} else {
		if def.null > C.sb2(-1) {
			var float64Value float64
			r := C.OCINumberToReal(
				def.rset.stmt.ses.srv.env.ocierr, //OCIError              *err,
				&def.ociNumber,                   //const OCINumber     *number,
				C.uword(8),                       //uword               rsl_length,
				unsafe.Pointer(&float64Value))    //void                *rsl );
			if r == C.OCI_ERROR {
				err = def.rset.stmt.ses.srv.env.ociError()
			}
			if err == nil {
                                // Detect if float64 value has decimal places
                                // If not return it as int64
				if math.Floor(float64Value) == float64Value {
					value = int64(float64Value)
				} else {
					value = float64Value
				}
			} else {
				value = float64Value
			}
		}
	}
	return value, err
}
```

**Comment by tgulacsi** [comment] 2016-02-18 14:19
Thanks @omerkirk! The "issue57" branch contains the suggested modification, and your test for it.

It should be tested in real-world apps, but I think it would solve the original problem, too.


A more demanding solution would be a defNumString, bndNumString ... which would use OCINumberToText and OCINumberFromText, and store the numbers as strings on Go side.
This would have the great pro: all Oracle numbers could be represented, without loss.

(Some time ago I've experimented with a Go side OCINumber implementation (22 bytes), which would allow conversion-free data exchange, and represent all Oracle-representable numbers, but failed with the bit-fiddling parts).

**Comment by omerkirk** [comment] 2016-02-18 15:47
Thanks @tgulacsi, I will try the code in the branch. Does the new branch include the changes for go1.6 compatibility too. Since in my project I have to use go1.6 for http/2. 

A Go side OCINumber sounds great, especially conversion free data exchange part. It would have huge benefits to query performance.

**Comment by omerkirk** [comment] 2016-02-18 15:55
By the way regarding your commit for defFloat64 I think your way of doing it in defFloat32 is much simpler. and minus a dependency.

**Comment by tgulacsi** [comment] 2016-02-18 16:10
I'm doing it with float32(int32(f)) == f 'cause math.Floor is for float64, and math.Floor(float64(f)) == float64(f) would be the same amount of conversion; for float64 numbers, math.Floor(f) == f is less conversion and I think it is faster, too.

That's what I thought :)

```go
$ cat ~/src/github.com/tgulacsi/go/x/x_test.go
package main_test

import (
        "math"
        "testing"
)

func BenchmarkF64Convert(b *testing.B) {
        f := float64(1.5)
        var t bool
        for i := 0; i < b.N; i++ {
                t = f == float64(int64(f))
        }
        b.Log(t)
}

func BenchmarkF64Floor(b *testing.B) {
        f := float64(1.5)
        var t bool
        for i := 0; i < b.N; i++ {
                t = f == math.Floor(f)
        }
        b.Log(t)
}
func BenchmarkF32Convert(b *testing.B) {
        f := float32(1.5)
        var t bool
        for i := 0; i < b.N; i++ {
                t = f == float32(int32(f))
        }
        b.Log(t)
}

func BenchmarkF32Floor(b *testing.B) {
        f := float32(1.5)
        var t bool
        for i := 0; i < b.N; i++ {
                x := float64(f)
                t = x == math.Floor(x)
        }
        b.Log(t)
}
```
BenchmarkF32Convert-4   2000000000               1.62 ns/op
BenchmarkF32Floor-4     300000000                4.39 ns/op
BenchmarkF64Convert-4   1000000000               1.69 ns/op
BenchmarkF64Floor-4     500000000                3.85 ns/op

I'll change in defFloat64.

**Comment by tgulacsi** [comment] 2016-02-20 07:11
@maliutin @omerkirk can you test the "issue57" branch? Does it help your use cases? Does it introduce problems?
I want some positive feedback before merging it into master!

**Comment by maliutin** [comment] 2016-02-20 11:27
@tgulacsi I tested "issue57" branch with our data. it is not working. It has very strange behavior. For example:

We have table:
```
CREATE TABLE ACCOUNT (
  ACCOUNT_ID NUMBER,
  CURRENT_BALANCE NUMBER(20, 4) NOT NULL,
  AVAILABLE_BALANCE NUMBER(20, 4),
...
```
This table contains two rows:

ACCOUNT_ID | CURRENT_BALANCE | AVAILABLE_BALANCE
---------- | --------------- | -----------------
1 | 94,5 | 94,5
2 | 0 | 0

We use the query
```
SELECT *  FROM account
```
For fist row the correct is following code
```
currentBalance := row[0].(float64)
availableBalance := row[1].(float64)
```
but for second row it returns the error:

> panic: interface conversion: interface is int64, not float64

If we change the code:
```
currentBalance := row[0].(int64)
availableBalance := row[1].(int64)
```
For second row we receive the values but for first row we have the error:

> panic: interface conversion: interface is float64, not int64

I think that second behavior is correct. But the first behavior in theory should work without error.

In GO conception you proposition about NUMBER and float64 is correct. Because the go can not contain the hidden conversion from int64 to float64.

**Comment by tgulacsi** [comment] 2016-02-20 12:45
That's what I'm afraid of. This patch changes the returned data type by each row - nice in theory, if you know that your data is always int, but fails when sometimes it is not integer...

**Comment by maliutin** [comment] 2016-02-20 13:31
> if you know that your data is always int, but fails when sometimes it is not integer...
In this case it means that we have a problem in data. The incoming data for our algorithms is incorrect.

Thus the second case when we assert that value is int64 we run our functionality if it is correct, otherwise, we report that the functionality of the database is implemented incorrectly.

But I think that problem is in GO, more precisely, the problem is in the conversion process. In GO we do not convert from value from interface{} to float64 if this value is int64. In the beginning we always have to do explicit type conversion from interface{}. In this case to int64 and only in next step we can convert  it to float64. GO does not have such type as Object in .NET or Java. And It can not implicitly convert from int64 to float64.

**Comment by maliutin** [comment] 2016-02-20 13:41
I suppose that Rset.Row should contain interface as in "database/sql":
```
type Row interface {
    Scan(value interface{}) error
}
```

```
var currentBalance float64
row[0].Scan(&currentBalance)
var availableBalance float64
row[1].Scan(&availableBalance)
```

**Comment by tgulacsi** [comment] 2016-02-20 19:00
Ok, so programs does not like when a column "changes" type: for one row the type is float64, for the next row it is int64.

I've added another solution in "numstring" branch: ora.Num and ora.OraNum, a string representation for the number. It uses OCINumberFromText and OCINumberToText (as goracle), so has maximum precision, no data loss. Moreover, database/sql automatically converts the string to the desired (numeric) type.

The only remaining thing to decide is that now this "N" (string) column type is the default for NUMBER(*) columns. Is this OK, or keep it F64 (float64) ?

**Comment by tgulacsi** [comment] 2016-02-21 20:31
Please check the "numstring" branch.

But everyone can change the default for numeric columns by 

```go
ora.Cfg().Env.StmtCfg.Rset.SetFloat(ora.N)
ora.Cfg().Env.StmtCfg.Rset.SetNumberFloat(ora.N)
```
or
```go
ora.Cfg().Env.StmtCfg.Rset.SetFloat(ora.I64)
ora.Cfg().Env.StmtCfg.Rset.SetNumberFloat(ora.I64)
```

**Comment by omerkirk** [comment] 2016-02-22 08:55
@tgulacsi I tried the numstring branch. Everything is working fine. Thanks for the quick update.

**Comment by tgulacsi** [comment] 2016-02-22 16:13
@maliutin, can you try it, too?

**Comment by maliutin** [comment] 2016-02-24 14:14
Hi, @tgulacsi 

> The only remaining thing to decide is that now this "N" (string) column type is the default for NUMBER(*) columns. Is this OK, or keep it F64 (float64) ?

It should be a string. It would be better if we had fewer conditions. It would be better if NUMBER is string for all conditions.

But I got "numstring" branch and tested. For NUMBER(*) it returns float64 for all settings:
> ora.Cfg().Env.StmtCfg.Rset.SetFloat(ora.N)
> ora.Cfg().Env.StmtCfg.Rset.SetNumberFloat(ora.N)
> or
> 
> ora.Cfg().Env.StmtCfg.Rset.SetFloat(ora.I64)
> ora.Cfg().Env.StmtCfg.Rset.SetNumberFloat(ora.I64)

**Comment by tgulacsi** [comment] 2016-02-25 21:31
Ok, I've created a simple test to see what do we get for different numeric column types, TestNumberTypes, and got:

"NUMBER"=(2) 0,-127
"NUMBER(*)"=(2) 0,-127
"NUMBER(1)"=(2) 1,0
"NUMBER(3,2)"=(2) 3,2
"NUMBER(*,4)"=(2) 38,4
"INT"=(2) 38,0
"BINARY_FLOAT"=(100) 0,0
"BINARY_DOUBLE"=(101) 0,0

I've rewritten numericColumType in rsetCfg.go according to this in the "issue57" branch.
Can you take a look? If you have some set where the result is not what you want, please give me the type,precision,scale tuple and the desired column type, and I'll see what we can do.
For the precision and scale either use the DescribeQuery function in z_oracle_test.go, or give the CREATE TABLE statement to reproduce it.

Thanks in advance!

**Comment by maliutin** [comment] 2016-02-29 08:56
@tgulacsi 

I have following result after test:
NUM - string
NUM_STAR - string
NUM_1 - int64
NUM_3_2 - float64
NUM_STAR_4 - string
INTE - string
FL - float32
DBL - float64

**Comment by tgulacsi** [comment] 2016-02-29 10:35
I think these results are correct. NUMBER(n) could use a narrower type (int8, int16, int32 based on n), but I think that makes this overcomplicated, and is not needed at all.

**Comment by tgulacsi** [comment] 2016-03-19 10:47
Hi,

I've implemented a memory-savy replacement of NumString, OCINum in the "ocinum" branch.
This stores the number just as Oracle gives in OCINumber, in a []byte slice, with at most 21 length. It is only used for resultsets at the moment.

A not-too-nice side effect of this change that where now the (long) number is returned as a string, it will be returned as an ora.OCINum. That implements the String() method, so database/sql users wouldn't notice the change, only direct ora users: instead of a .(string), they'd have to use .(OCINum).String().

What are your opinion? I'm inclined to merge this in the near future (space savings and sidesteps the number formatting issue with huge numbers).

Thanks in advance!

**Comment by tgulacsi** [comment] 2016-04-08 05:26
This "ocinum" branch is now merged into master, will be in v3.4, if no oppositions!

**Comment by rana** [comment] 2016-04-08 15:22
Thank you Tamas, sounds good

**Comment by tgulacsi** [comment] 2016-04-09 10:25
Tagged v3.4

**Closed by tgulacsi** 2016-04-09 10:25 UTC
