### ISSUE TITLE
alternative to calling stored procedure without using OUT parameter SYS_REFCURSOR to retrieve results

### ISSUE THREAD

**Issue by crisarceramos** [rana/ora#59] opened 2016-02-11 07:25 UTC
Hi dev team, 
This is not an issue but can you provide an example where ora.v3 executes a stored procedure that does not return a SYS_REFCURSOR. Instead, stored procedure executes a simple SELECT statement and the golang app with ora.v3 can retrieve these rows? I am having slow performance using SYS_REFCURSOR for a simple select query. It seems ora.Rset,Next() is slow.

Thanks!

**Comment by tgulacsi** [comment] 2016-02-11 10:58
a) shovel all data in an OUT VARCHAR2(32767) parameter (or CLOB),
b) use my not-yet-merged ("slice" branch) changes to return a TYPE xx_tab_typ VARCHAR2(32767) INDEX BY PLS_INTEGER
c) help us speed up Rset.Next: provide a repro, or profile it yourself!

**Comment by crisarceramos** [comment] 2016-02-12 12:54
Thanks tgulacsi. Just to be clear with a), u mean to change SYS_REFCURSOR to VARCHAR2(32767) right? But inside stored proc, how do u store result of a SELECT query in a VARCHAR2 ?

**Comment by tgulacsi** [comment] 2016-02-12 14:27
"SELECT a||';'||b||';'", or create an XML with the built-in methods ... I haven't said it's a nice solution - just a barely workable one...

**Comment by tgulacsi** [comment] 2016-02-12 14:29
How slow is it? Do you retrieve a lot of simple (one small field, like a VARCHAR2(1)) rows? 
Maybe the conversion is slow? What are the data types?

**Comment by crisarceramos** [comment] 2016-02-17 05:40
i get this execution timestamp below. i already modified the SP to return Varchar2 and get that from a string variable in golang. unfortunately, still slow. but when i execute SP on sqldev, i get fast result. not sure why. SP constantly return 30+ rows and 4 columns. 

executing sp:20160217132405
executing complete:20160217132735

**Comment by tgulacsi** [comment] 2016-02-17 06:42
What are these numbers? 3 minutes difference?

Can you share code?

**Comment by crisarceramos** [comment] 2016-02-17 06:58
yes 3mins. sometimes 5mins. not sure what's going on honestly. below is the code that executes the SP.

`func (oracleDB *oracleDB) executeOraSP(ses *ora.Ses) string {
	if nil == ses {
		ses = oracleDB.mSes
	}

	var strResult string
	mStmt, err := ses.Prep("CALL " + *sp + "(:1, :PARAM1, :PARAM2, :PARAM3)")

	if nil == err {
		//split param
		var params = strings.Fields(*spPar)

		if len(params) == 3 {
			t := time.Now()
			fmt.Println("executing sp:" + t.Format("20060102150405"))
			_, err := mStmt.Exe(&strResult, params[0], params[1], params[2])
			t = time.Now()
			fmt.Println("executing complete:" + t.Format("20060102150405"))
			if nil != err {
				oracleDB.mErr = err
			}
		} else {
			oracleDB.mErr = errors.New("Incomplete SP parameter!")
		}
	} else {
		oracleDB.mErr = err
	}

	return strResult
}
`

**Comment by tgulacsi** [comment] 2016-02-17 08:42
I see nothing esp. fishy with your code; can you add more logging? Sthg like

```go

import "gopkg.in/rana/ora.v3/lg"

func init() {
		drvCfg := ora.NewDrvCfg()
		drvCfg.Log.Logger = lg.Log
		ora.SetDrvCfg(drvCfg)
}

func (oracleDB *oracleDB) executeOraSP(ses *ora.Ses) string {                                                                                                                                                                                 
    if ses == ses {                                                                                                                                                                                                                           
        ses = oracleDB.mSes                                                                                                                                                                                                                   
    }
                                                                                                                                                                                                                                              
    qry := "CALL " + *sp + "(:1, :PARAM1, :PARAM2, :PARAM3)"                                                                                                                                                                                  
    mStmt, err := ses.Prep(qry)                                                                                                                                                                                                               
    if err != nil {                                                                                                                                                                                                                           
        oracleDB.mErr = err                                                                                                                                                                                                                   
        return ""                                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                              
    //split param                                                                                                                                                                                                                             
    var params = strings.Fields(*spPar)                                                                                                                                                                                                       
                                                                                                                                                                                                                                              
    if len(params) != 3 {                                                                                                                                                                                                                     
        oracleDB.mErr = errors.New("Incomplete SP parameter!")                                                                                                                                                                                
        return ""                                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                         
    params := []interface{}{&strResult, params[0], params[1], params[2]}                                                                                                                                                                      
    t := time.Now()                                                                                                                                                                                                                           
    fmt.Printf("Start executing %q %#v at %s...\n", qry, params, t.Format("20060102_150405"))                                                                                                                                                 
    var strResult string                                                                                                                                                                                                                      
    _, err := mStmt.Exe(params...)                                                                                                                                                                                                            
    d := time.Since(t)                                                                                                                                                                                                                        
    if err != nil {                                                                                                                                                                                                                           
        fmt.Printf("execution error: %v\n", err)                                                                                                                                                                                              
        oracleDB.mErr = err                                                                                                                                                                                                                   
        return ""                                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                         
    fmt.Printf("execution completed in %s, result: %q.", d, strResult)                                                                                                                                                                        
    return strResult                                                                                                                                                                                                                          
}
```

It is quite strange that a stored procedure call has anything more than a few milliseconds of overhead...

**Comment by crisarceramos** [comment] 2016-02-17 11:57
Thanks tgulacsi! Really appreciate your time and effort to help. Below is what I get from the logs.

```
ORA I 2016/02/17 19:40:21.282303 util.go:179: [gopkg.in/rana/ora%2ev3.OpenEnv]
ORA I 2016/02/17 19:40:21.285075 env.go:299: E2 [Env.OpenSrv]
ORA I 2016/02/17 19:40:23.921919 srv.go:322: E2S1 [Srv.OpenSes]
ORA I 2016/02/17 19:40:25.201767 ses.go:637: E2S1S1 [Ses.Prep] CALL PROC_PRTG_HZ_KPI(:1, :PARAM1, :PARAM2, :PARAM3)
Start executing "CALL SP_NAME(:1, :PARAM1, :PARAM2, :PARAM3)" []string{"sometext", "sometext%", "sometext"} at 20160217_194025...
ORA I 2016/02/17 19:40:25.202519 stmt.go:1116: E2S1S1S1 [Stmt.exe]
ORA I 2016/02/17 19:40:25.202546 stmt.go:1129: E2S1S1S1 [Stmt.bind] Params 4
ORA I 2016/02/17 19:40:25.202718 stmt.go:1129: E2S1S1S1 [bndStringPtr.bind] StringPtr.bind(1) cap=1000 len=1 alen=0
ORA I 2016/02/17 19:49:04.079039 stmt.go:1129: E2S1S1S1 [bndStringPtr.setPtr] StringPtr.setPtr isNull=1051 alen=1000
execution completed in 8m38.876753193s, result: "\nSometext;0;0;Count\n".<nil>          //the result is just a repeated like this. 1000+characters

Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;Count
Sometext;0;0;                           <--this result string is always truncated not sure why, maybe because of the cap??
ORA I 2016/02/17 19:49:04.080678 ses.go:635: E2S1S1 [Ses.close]
ORA I 2016/02/17 19:49:04.080708 stmt.go:1116: E2S1S1S1 [Stmt.close]
ORA I 2016/02/17 19:49:04.379058 srv.go:322: E2S1 [Srv.close]
ORA I 2016/02/17 19:49:04.380475 env.go:299: E2 [Env.Close]
Success: process exited with code 0.

```

**Comment by tgulacsi** [comment] 2016-02-17 12:04
Just to narrow things down: 
which version of go?
which version (commit) of ora?
I'm asking this 'cause I've met some great slow-down with go 1.6.

Can you share the stored procedure's sekeleton (in and out types), maybe a test version which does reproduce the problem in your env?

**Comment by crisarceramos** [comment] 2016-02-17 13:41
go version go1.5.1 linux/amd64
for ora, i just perform go get -u all last week.
Linux: Elementary OS Freya

SP skeleton:
```
create or replace PROCEDURE PROC_NAME(THEOUTPUT OUT VARCHAR2, PARAM1 IN VARCHAR2, PARAM2 IN VARCHAR2, PARAM3 IN VARCHAR2) AS
--declare multiple VARCHAR2 variable containing select statements, at the end combine these based from IF-ELS and execute with below:

  EXECUTE IMMEDIATE STATQUERY
  BULK COLLECT
  INTO channels;
  FOR i IN channels.FIRST..channels.LAST
  LOOP
      TEMPSTR:=TEMPSTR||CHR(10)||channels(i).channeldata;
  END LOOP;
  
  THEOUTPUT:=TEMPSTR;
END;
```

**Comment by tgulacsi** [comment] 2016-02-17 21:27
Hi, I can't reproduce it on my test db.

1. What is the env where you run it? Is this the only program running?
2. Can you reproduce it on my test db? It's at test/test@git.gthomas.eu:49161 - it runs in a container, and is erased every hour. 
If you can, then a reproduction case would be great help!
If you cannot, then maybe the differences between the DB envs can shed some light.

**Comment by tgulacsi** [comment] 2016-02-26 18:06
Ok, I've misled you, sorry.

database/sql is does not allow to use it with returning values by using pointers: it simply dereferences them...

So I've added a TestSessionCallPkg as an example.

**Closed** 2016-03-01 13:11 UTC

**Comment by crisarceramos** [comment] 2016-03-04 15:42
thanks alot!
